//Redux에서 쓰일 type 지정
//Saga쓸때는 따로 써야함

//Login - REQUEST하고 나면 SUCCESS or FAILURE이 됨
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

//ERROR CLEAR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST"
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS"
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE"
